### ISSUE TITLE
Info-Embed wont be posted if User has to much Roled

### ISSUE THREAD

**Issue by R3TRO04** [PKlempe/SAM#244]
**Info**

Info-Embed does not show up if a user has too many roles. This is caused by exceeding the Char limit of the Embed.

**Suggested Solution** 

Limit the number of shown Roles and show a short info that there are more roles for example:

> 10+ more roles

**Comment by Katakompe** [comment]
Additional note: The problem occurs because the character limit of the role field in the embed is hit. This is 1024 characters, however longer strings can be displayed because the character limit actually is on the string, which just contains role ids in the shape '<@213651561..> <@123...> ...', making it possible to show more characters if the role names were longer than that.
